Task 1: Identify and Characterize Data Sources

In [86]:
dataset_a = [
    {"username": "alice123", "email": "alice@example.com", "age": 25, "signup_date": "2026-01-10"},
    {"username": "bob_smith", "email": "bob.smith@example.com", "age": 30, "signup_date": "2026-01-12"},
    {"username": "", "email": "charlie@example.com", "age": 22, "signup_date": "2026-01-15"},  # Empty username
    {"username": "david99", "email": "david.example.com", "age": 28, "signup_date": "2026-01-18"},  # Invalid email
    {"username": "eve2026", "email": "eve@example.com", "age": "twenty-four", "signup_date": "2026-01-20"},  # Age as string
    {"username": "frankie", "email": "frankie@example.com", "age": 35, "signup_date": "2026-01-22"},
    {"username": "grace_h", "email": "grace@example.com", "age": 27, "signup_date": "2026-01-25"},
    {"username": "henry_k", "email": "henry.k@example.com", "age": 31, "signup_date": "2026-01-28"}
]

user input 
----------------------
1. invalid or missing fields (e.g empty e-mail)
2. incorrect datatypes (e.g str for age column)
3. duplicate accounts
------------------------
1. check all fields are present and not empty
2. data type validation(e.g age column doesnt have a str value)
3. format validation - email contains @ 
4. duplicate detection
5. age in reasonable range

In [87]:
dataset_b = [
    {"timestamp": "2026-02-28 08:15:23", "service": "auth_service", "level": "INFO", "message": "User login successful"},
    {"timestamp": "2026-02-28 08:17:45", "service": "auth_service", "level": "WARNING", "message": "Multiple failed login attempts"},
    {"timestamp": "2026-02-28 08:20:01", "service": "payment_service", "level": "ERROR", "message": "Payment processing failed"},
    {"timestamp": "2026-02-28 08:22:12", "service": "payment_service", "level": "INFO", "message": "Payment completed for order #1023"},
    {"timestamp": "2026-02-28 08:25:30", "service": "notification_service", "level": "INFO", "message": "Email sent to user alice@example.com"},
    {"timestamp": "2026-02-28 08:27:18", "service": "notification_service", "level": "ERROR", "message": "Push notification failed"},
    {"timestamp": "2026-02-28 08:30:05", "service": "auth_service", "level": "INFO", "message": "Password reset requested"},
    {"timestamp": "2026-02-28 08:32:47", "service": "payment_service", "level": "WARNING", "message": "Payment gateway response delayed"},
    {"timestamp": "2026-02-28 08:35:12", "service": "notification_service", "level": "INFO", "message": "SMS sent to user bob_smith"},
    {"timestamp": "2026-02-28 08:37:50", "service": "auth_service", "level": "ERROR", "message": "Account locked due to suspicious activity"}
]

system-generated data
-------------------------
1. missing log fields
2. incorrect time formats
3. duplicate logs 
4. volume challenges
5. processing complexity
-------------------------
1. check all required fields present and not null
2. timestamp validation
3. name consistency

In [88]:
dataset_c = [
    {"sku": "P1001", "product_name": "Wireless Mouse", "quantity_in_stock": 150, "warehouse_location": "A1", "last_updated": "2026-02-25"},
    {"sku": "P1002", "product_name": "Mechanical Keyboard", "quantity_in_stock": 80, "warehouse_location": "A2", "last_updated": "2026-02-26"},
    {"sku": "P1003", "product_name": "HD Monitor 24\"", "quantity_in_stock": 45, "warehouse_location": "B1", "last_updated": "2026-02-24"},
    {"sku": "P1004", "product_name": "USB-C Hub", "quantity_in_stock": 200, "warehouse_location": "B2", "last_updated": "2026-02-27"},
    {"sku": "P1005", "product_name": "External SSD 1TB", "quantity_in_stock": 60, "warehouse_location": "C1", "last_updated": "2026-02-25"},
    {"sku": "P1006", "product_name": "Gaming Chair", "quantity_in_stock": 15, "warehouse_location": "C2", "last_updated": "2026-02-26"}
]

internal database
-------------------------------
1. Coordination challenges
2. Data quality
3. negative/unrealistic stock quantities
4. missing or incorrect sku or product names
--------------
1. check all required fields present and non null 
2. check quantity in stock is numeric 
3. sku is unique per product

Step 3:

In [89]:
def validate_registrations(entries):
    valid_entries = []
    invalid_entries = []

    for entry in entries:
        try:
            username = entry.get('username', '').strip()
            email = entry.get('email', '').strip()
            age = entry.get('age')

            if not username:
                raise ValueError("Empty Username")
            if "@" not in email:
                raise ValueError("Invalid Email")
            if int(age)<=0:
                raise ValueError("Age must be positive")
            valid_entries.append(entry)

        except Exception:
            invalid_entries.append(entry)
    return valid_entries, invalid_entries        
dataset_a = dataset_a
valid_entries, invalid_entries = validate_registrations(dataset_a)

print("Valid entries count:", len(valid_entries))
print("Invalid entries count:", len(invalid_entries))

Valid entries count: 5
Invalid entries count: 3

Task 2: Work with Multiple Data Formats

In [90]:
import pandas as pd 
import numpy as np

np.random.seed(42)
n_rows = 500

rides = pd.DataFrame({
    'ride_id' : np.arange(1, n_rows+1), 
    'driver_id' : np.random.randint(1000, 1051, size=n_rows), 
    'distance_km' : np.random.uniform(1.0, 3.0, size=n_rows),
    'fare_usd': np.random.uniform(5.0, 75.0, size=n_rows), 
    'ride_type': np.random.choice(['standard', 'premium', 'pool']),
    'city': np.random.choice(['Berlin', 'Seoul', 'Nairobi', 'Toronto', 'Lima']),
    'timestamp': pd.date_range(start="2025-01-01", periods=n_rows, freq='T')
})
rides

C:\Users\ikinci.el.noutbuklar\AppData\Local\Temp\ipykernel_6192\3837723073.py:14: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  'timestamp': pd.date_range(start="2025-01-01", periods=n_rows, freq='T')

,ride_id,driver_id,distance_km,fare_usd,ride_type,city,timestamp
0,1,1038,1.183598,45.434237,standard,Nairobi,2025-01-01 00:00:00
1,2,1028,1.188314,16.585932,standard,Nairobi,2025-01-01 00:01:00
2,3,1014,1.622827,7.371541,standard,Nairobi,2025-01-01 00:02:00
3,4,1042,2.959021,26.803122,standard,Nairobi,2025-01-01 00:03:00
4,5,1007,1.350661,59.634700,standard,Nairobi,2025-01-01 00:04:00
...,...,...,...,...,...,...,...
495,496,1050,2.836909,8.056316,standard,Nairobi,2025-01-01 08:15:00
496,497,1036,2.174136,16.317078,standard,Nairobi,2025-01-01 08:16:00
497,498,1021,1.065693,6.460280,standard,Nairobi,2025-01-01 08:17:00
498,499,1028,2.825499,50.728411,standard,Nairobi,2025-01-01 08:18:00
499,500,1013,1.496453,28.262024,standard,Nairobi,2025-01-01 08:19:00

In [91]:
rides.to_csv('rides.csv', index=False)

rides.to_json('rides.json', orient='records', lines=True)

rides.to_parquet('rides.parquet', index=False)

In [92]:
import os

In [93]:
csv_size = os.path.getsize('rides.csv') / 1024
json_size = os.path.getsize('rides.json') / 1024
parquet_size = os.path.getsize('rides.parquet') /1024
csv_size, json_size, parquet_size

(40.9169921875, 73.47265625, 20.4248046875)

In [94]:
csv_size/parquet_size

2.003299067654793

In [95]:
rides_csv = pd.read_csv('rides.csv')
rides_csv

,ride_id,driver_id,distance_km,fare_usd,ride_type,city,timestamp
0,1,1038,1.183598,45.434237,standard,Nairobi,2025-01-01 00:00:00
1,2,1028,1.188314,16.585932,standard,Nairobi,2025-01-01 00:01:00
2,3,1014,1.622827,7.371541,standard,Nairobi,2025-01-01 00:02:00
3,4,1042,2.959021,26.803122,standard,Nairobi,2025-01-01 00:03:00
4,5,1007,1.350661,59.634700,standard,Nairobi,2025-01-01 00:04:00
...,...,...,...,...,...,...,...
495,496,1050,2.836909,8.056316,standard,Nairobi,2025-01-01 08:15:00
496,497,1036,2.174136,16.317078,standard,Nairobi,2025-01-01 08:16:00
497,498,1021,1.065693,6.460280,standard,Nairobi,2025-01-01 08:17:00
498,499,1028,2.825499,50.728411,standard,Nairobi,2025-01-01 08:18:00
499,500,1013,1.496453,28.262024,standard,Nairobi,2025-01-01 08:19:00

In [96]:
rides_json = pd.read_json('rides.json', lines=True)
rides_json

,ride_id,driver_id,distance_km,fare_usd,ride_type,city,timestamp
0,1,1038,1.183598,45.434237,standard,Nairobi,2025-01-01 00:00:00
1,2,1028,1.188314,16.585932,standard,Nairobi,2025-01-01 00:01:00
2,3,1014,1.622827,7.371541,standard,Nairobi,2025-01-01 00:02:00
3,4,1042,2.959021,26.803122,standard,Nairobi,2025-01-01 00:03:00
4,5,1007,1.350661,59.634700,standard,Nairobi,2025-01-01 00:04:00
...,...,...,...,...,...,...,...
495,496,1050,2.836909,8.056316,standard,Nairobi,2025-01-01 08:15:00
496,497,1036,2.174136,16.317078,standard,Nairobi,2025-01-01 08:16:00
497,498,1021,1.065693,6.460280,standard,Nairobi,2025-01-01 08:17:00
498,499,1028,2.825499,50.728411,standard,Nairobi,2025-01-01 08:18:00
499,500,1013,1.496453,28.262024,standard,Nairobi,2025-01-01 08:19:00

In [97]:
try:
    rides_parquet = pd.read_parquet('rides.parquet')
    parquet_status = "Successfully loaded"
except ImportError:
    parquet_status = "Pyarrow is missing "

In [98]:
rides_parquet

,ride_id,driver_id,distance_km,fare_usd,ride_type,city,timestamp
0,1,1038,1.183598,45.434237,standard,Nairobi,2025-01-01 00:00:00
1,2,1028,1.188314,16.585932,standard,Nairobi,2025-01-01 00:01:00
2,3,1014,1.622827,7.371541,standard,Nairobi,2025-01-01 00:02:00
3,4,1042,2.959021,26.803122,standard,Nairobi,2025-01-01 00:03:00
4,5,1007,1.350661,59.634700,standard,Nairobi,2025-01-01 00:04:00
...,...,...,...,...,...,...,...
495,496,1050,2.836909,8.056316,standard,Nairobi,2025-01-01 08:15:00
496,497,1036,2.174136,16.317078,standard,Nairobi,2025-01-01 08:16:00
497,498,1021,1.065693,6.460280,standard,Nairobi,2025-01-01 08:17:00
498,499,1028,2.825499,50.728411,standard,Nairobi,2025-01-01 08:18:00
499,500,1013,1.496453,28.262024,standard,Nairobi,2025-01-01 08:19:00

In [99]:
rides_csv.shape

(500, 7)

In [100]:
rides_json.shape

(500, 7)

In [101]:
rides_parquet.shape

(500, 7)

In [102]:
print('CSV file: ')
print(rides_csv.head())

CSV file:
   ride_id  driver_id  distance_km   fare_usd ride_type     city  \
0        1       1038     1.183598  45.434237  standard  Nairobi
1        2       1028     1.188314  16.585932  standard  Nairobi
2        3       1014     1.622827   7.371541  standard  Nairobi
3        4       1042     2.959021  26.803122  standard  Nairobi
4        5       1007     1.350661  59.634700  standard  Nairobi

             timestamp
0  2025-01-01 00:00:00
1  2025-01-01 00:01:00
2  2025-01-01 00:02:00
3  2025-01-01 00:03:00
4  2025-01-01 00:04:00

In [103]:
print('JSON file')
print(rides_json.head())

JSON file
   ride_id  driver_id  distance_km   fare_usd ride_type     city  \
0        1       1038     1.183598  45.434237  standard  Nairobi
1        2       1028     1.188314  16.585932  standard  Nairobi
2        3       1014     1.622827   7.371541  standard  Nairobi
3        4       1042     2.959021  26.803122  standard  Nairobi
4        5       1007     1.350661  59.634700  standard  Nairobi

            timestamp
0 2025-01-01 00:00:00
1 2025-01-01 00:01:00
2 2025-01-01 00:02:00
3 2025-01-01 00:03:00
4 2025-01-01 00:04:00

In [104]:
print('Parquet file')
print(rides_parquet.head())

Parquet file
   ride_id  driver_id  distance_km   fare_usd ride_type     city  \
0        1       1038     1.183598  45.434237  standard  Nairobi
1        2       1028     1.188314  16.585932  standard  Nairobi
2        3       1014     1.622827   7.371541  standard  Nairobi
3        4       1042     2.959021  26.803122  standard  Nairobi
4        5       1007     1.350661  59.634700  standard  Nairobi

            timestamp
0 2025-01-01 00:00:00
1 2025-01-01 00:01:00
2 2025-01-01 00:02:00
3 2025-01-01 00:03:00
4 2025-01-01 00:04:00

Parquet maintains data types most accurately and results in the smallest file sizes. CSV is simple to read but can lose type information, whereas JSON is better suited for structured data but is less storage-efficient. Parquet is ideal for large datasets and machine learning workflows, CSV works well for straightforward data sharing, and JSON is commonly used for APIs and logging.1

Task 3: Row-major vs Column-Major Access Patterns

In [105]:
np.random.seed(42)
n_rows = 200_000
n_cols = 20
columns = [f"feature_{i}" for i in range(n_cols)]
df = pd.DataFrame(
    np.random.rand(n_rows, n_cols),  # values between 0 and 1
    columns=columns
)
print(df.head())
print("\nShape:", df.shape)

   feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0   0.374540   0.950714   0.731994   0.598658   0.156019   0.155995
1   0.611853   0.139494   0.292145   0.366362   0.456070   0.785176
2   0.122038   0.495177   0.034389   0.909320   0.258780   0.662522
3   0.388677   0.271349   0.828738   0.356753   0.280935   0.542696
4   0.863103   0.623298   0.330898   0.063558   0.310982   0.325183

   feature_6  feature_7  feature_8  feature_9  feature_10  feature_11  \
0   0.058084   0.866176   0.601115   0.708073    0.020584    0.969910
1   0.199674   0.514234   0.592415   0.046450    0.607545    0.170524
2   0.311711   0.520068   0.546710   0.184854    0.969585    0.775133
3   0.140924   0.802197   0.074551   0.986887    0.772245    0.198716
4   0.729606   0.637557   0.887213   0.472215    0.119594    0.713245

   feature_12  feature_13  feature_14  feature_15  feature_16  feature_17  \
0    0.832443    0.212339    0.181825    0.183405    0.304242    0.524756
1    0.065052    0.948886    0.965632    0.808397    0.304614    0.097672
2    0.939499    0.894827    0.597900    0.921874    0.088493    0.195983
3    0.005522    0.815461    0.706857    0.729007    0.771270    0.074045
4    0.760785    0.561277    0.770967    0.493796    0.522733    0.427541

   feature_18  feature_19
0    0.431945    0.291229
1    0.684233    0.440152
2    0.045227    0.325330
3    0.358466    0.115869
4    0.025419    0.107891

Shape: (200000, 20)

In [106]:
%time df["feature_0"].mean()

CPU times: total: 0 ns
Wall time: 3.15 ms

np.float64(0.4999447361213433)

In [107]:
%%timeit
total = 0
for i in range(10000):
    total += df.iloc[i]["feature_0"]

112 ms ± 3.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [108]:
arr = df.to_numpy()
%time arr[:, 0].mean()
# Expected: ~50-100 microseconds (Fastest)

CPU times: total: 0 ns
Wall time: 1.6 ms

np.float64(0.4999447361213433)

In [109]:
%%timeit
total = 0
for i in range(10000):
    total += arr[i, 0]
# Expected: ~2-5 milliseconds (Much faster than Pandas row access)

1.52 ms ± 298 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

Why is column access in pandas so much faster than row iteration?
Why does the gap narrow (or change) when using NumPy?
What does this tell you about how pandas and NumPy lay out data in memory?


Pandas is designed for column-wise operations, so accessing an entire column benefits from fast, vectorized computations. Iterating over rows is slower because each row access creates a pandas Series object, introducing additional Python-level overhead.
NumPy arrays are stored in contiguous memory, making both row and column access more efficient compared to pandas. The performance difference arises because NumPy avoids the extra object overhead that pandas incurs.
Overall, both libraries are optimized for column-based operations. NumPy stores data in compact, homogeneous arrays, while pandas builds on NumPy but adds extra structure, which slows down row access.

Task 4: Text vs Binary Format Deep Dive

In [110]:
import pandas as pd
import numpy as np
import os

np.random.seed(42)
rows = 100_000
data = {
    'f1': np.random.randn(rows),
    'f2': np.random.randn(rows),
    'f3': np.random.randn(rows),
    'f4': np.random.randn(rows),
    'f5': np.random.randn(rows),
    'category': np.random.choice(["alpha", "beta", "gamma"], size=rows)
}
df = pd.DataFrame(data)

In [111]:
df.to_csv("data.csv", index=False)
df.to_parquet("data.parquet", index=False)

csv_size = os.path.getsize("data.csv") / (1024**2)
pq_size = os.path.getsize("data.parquet") / (1024**2)

print(f"CSV Size: {csv_size:.2f} MB")     # ~11-12 MB
print(f"Parquet Size: {pq_size:.2f} MB") # ~4-5 MB (roughly 60% smaller)

CSV Size: 10.00 MB
Parquet Size: 4.86 MB

In [112]:
df_csv = pd.read_csv("data.csv")
df_pq = pd.read_parquet("data.parquet")

print(df_csv.dtypes)
print(df_pq.dtypes)

f1          float64
f2          float64
f3          float64
f4          float64
f5          float64
category     object
dtype: object
f1          float64
f2          float64
f3          float64
f4          float64
f5          float64
category     object
dtype: object

In [113]:
%time pd.read_csv("data.csv")

%time pd.read_parquet("data.parquet")

CPU times: total: 125 ms
Wall time: 154 ms
CPU times: total: 15.6 ms
Wall time: 19.6 ms

             f1        f2        f3        f4        f5 category
0      0.496714  1.030595  1.561841 -1.399822  3.035426     beta
1     -0.138264 -1.155355 -0.094228  0.547823 -0.148098    alpha
2      0.647689  0.575437 -1.329536 -0.120762 -1.731758    alpha
3      1.523030 -0.619238 -1.388638 -0.283264  0.515039    gamma
4     -0.234153 -0.327403 -0.342651  0.767569 -0.063741    gamma
...         ...       ...       ...       ...       ...      ...
99995 -0.225225 -1.264548 -0.432314 -0.554456  1.333620     beta
99996 -0.569778  0.565654 -0.687466 -2.316381 -0.109756    alpha
99997  0.409185  0.160020 -0.679638  0.831556 -0.243695    alpha
99998 -0.211092  0.855673 -1.072092  0.462531 -0.797460     beta
99999  0.120063 -1.064948 -0.357846 -0.137357 -1.641133     beta

[100000 rows x 6 columns]

In [114]:
%time pd.read_parquet("data.parquet", columns=["category"])

CPU times: total: 15.6 ms
Wall time: 14.5 ms

      category
0         beta
1        alpha
2        alpha
3        gamma
4        gamma
...        ...
99995     beta
99996    alpha
99997    alpha
99998     beta
99999     beta

[100000 rows x 1 columns]

Task 5

In [115]:
import pandas as pd

# Step 1: Flat (Denormalized) DataFrame
flat_data = [
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "format": "Paperback", "pub_name": "Scribner", "pub_country": "USA", "price": 15.00},
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "format": "E-book", "pub_name": "Scribner", "pub_country": "USA", "price": 9.99},
    {"title": "1984", "author": "George Orwell", "format": "Paperback", "pub_name": "Secker & Warburg", "pub_country": "UK", "price": 12.50},
    {"title": "1984", "author": "George Orwell", "format": "E-book", "pub_name": "Secker & Warburg", "pub_country": "UK", "price": 8.99},
    {"title": "Brave New World", "author": "Aldous Huxley", "format": "Paperback", "pub_name": "Chatto & Windus", "pub_country": "UK", "price": 14.00},
    # ... (Imagine 7 more rows for brevity)
]
df_flat = pd.DataFrame(flat_data)

# Step 2: Normalized Version
publishers = pd.DataFrame([
    {"pub_id": 1, "pub_name": "Scribner", "pub_country": "USA"},
    {"pub_id": 2, "pub_name": "Secker & Warburg", "pub_country": "UK"},
    {"pub_id": 3, "pub_name": "Chatto & Windus", "pub_country": "UK"}
])

books = pd.DataFrame([
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "format": "Paperback", "pub_id": 1, "price": 15.00},
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "format": "E-book", "pub_id": 1, "price": 9.99},
    {"title": "1984", "author": "George Orwell", "format": "Paperback", "pub_id": 2, "price": 12.50},
    {"title": "1984", "author": "George Orwell", "format": "E-book", "pub_id": 2, "price": 8.99},
])

# Verification Join
df_reconstructed = books.merge(publishers, on="pub_id")

In [116]:
catalog = [
    {
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "publisher": {"name": "Scribner", "country": "USA"},
        "editions": [
            {"format": "Paperback", "price": 15.00},
            {"format": "E-book", "price": 9.99}
        ]
    },
    {
        "title": "1984",
        "author": "George Orwell",
        "publisher": {"name": "Secker & Warburg", "country": "UK"},
        "editions": [
            {"format": "Paperback", "price": 12.50},
            {"format": "E-book", "price": 8.99}
        ]
    }
]